### ISSUE TITLE
希望网页版增加背景音乐

### ISSUE THREAD

**Issue by dyxang** [openinteg/deadline99#1]
建议：
全程BGM增加：紧张但不突兀，音量较小
回合倒计时BGM增加：倒计时音效
胜利与失败/出局音效增加

其实有很多无版权音效/音乐素材网站

**Comment by openinteg** [comment]
@dyxang 我先了解看看，有推荐欢迎告诉我。

**Comment by openinteg** [comment]
@dyxang 增加音效了
